#!/usr/bin/env bash
set -euo pipefail
set +x
umask 077

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
DEPLOY_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
COMPOSE_FILE="${COMPOSE_FILE:-$DEPLOY_DIR/docker-compose.yml}"
ENV_FILE="${ENV_FILE:-$DEPLOY_DIR/.env}"

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

compose() {
  docker compose --env-file "$ENV_FILE" --file "$COMPOSE_FILE" "$@"
}

database_version() {
  compose exec -T mysql sh -ceu '
    MYSQL_PWD="$MYSQL_ROOT_PASSWORD" exec mysql --user=root --batch --skip-column-names \
      "$MYSQL_DATABASE" --execute \
      "SELECT COALESCE(MAX(CAST(version AS UNSIGNED)), 0) FROM flyway_schema_history WHERE success = 1"
  '
}

[[ $# -eq 1 ]] || die "Usage: ROLLBACK_TARGET=production $0 /absolute/release-evidence/DIRECTORY"
[[ "${ROLLBACK_TARGET:-deny}" == "production" ]] \
  || die "Image rollback is disabled by default; set ROLLBACK_TARGET=production for this command only"
evidence_directory="$1"
[[ "$evidence_directory" == /* && -d "$evidence_directory" && ! -L "$evidence_directory" ]] \
  || die "Evidence directory must be an existing absolute non-symlinked directory"
[[ -f "$evidence_directory/.edu-admin-release-evidence" ]] || die "Evidence marker is missing"
state_file="$evidence_directory/release-state.env"
[[ -f "$state_file" && ! -L "$state_file" ]] || die "Release state is missing or unsafe"
[[ -f "$ENV_FILE" && ! -L "$ENV_FILE" ]] || die "Deployment .env is missing or unsafe"

# The state file is generated by release-production.sh from validated image
# references and numeric versions. Reject it before sourcing.
while IFS='=' read -r key value; do
  case "$key" in
    PREVIOUS_BACKEND_IMAGE|PREVIOUS_WEB_IMAGE)
      [[ "$value" =~ ^[A-Za-z0-9._:/@-]+$|^none$ ]] || die "Invalid image reference in release state"
      ;;
    PREVIOUS_SCHEMA_VERSION|TARGET_SCHEMA_VERSION)
      [[ "$value" =~ ^[0-9]+$ ]] || die "Invalid schema version in release state"
      ;;
    TARGET_IMAGE_TAG)
      [[ "$value" =~ ^[A-Za-z0-9._-]+$ ]] || die "Invalid image tag in release state"
      ;;
    *) die "Unexpected key in release state: $key" ;;
  esac
done < "$state_file"
# shellcheck disable=SC1090
source "$state_file"
[[ "$PREVIOUS_BACKEND_IMAGE" != "none" && "$PREVIOUS_WEB_IMAGE" != "none" ]] \
  || die "No previous running images were recorded"

current_schema_version="$(database_version | tr -d '[:space:]')"
[[ "$current_schema_version" == "$PREVIOUS_SCHEMA_VERSION" ]] || die \
  "Database changed from version $PREVIOUS_SCHEMA_VERSION to $current_schema_version; image rollback is unsafe. Apply a forward database repair."

confirmation_phrase="ROLLBACK IMAGES TO $PREVIOUS_SCHEMA_VERSION"
printf 'This changes application images only; database and uploads are untouched.\n' >&2
printf 'Type exactly: %s\n' "$confirmation_phrase" >&2
[[ -t 0 ]] || die "Image rollback requires an interactive TTY"
IFS= read -r confirmation || die "Confirmation was not received"
[[ "$confirmation" == "$confirmation_phrase" ]] || die "Confirmation did not match; nothing was changed"

export BACKEND_IMAGE="$PREVIOUS_BACKEND_IMAGE"
export WEB_IMAGE="$PREVIOUS_WEB_IMAGE"
compose pull backend web
compose up -d --remove-orphans backend web caddy

healthy=0
for _ in $(seq 1 60); do
  backend_id="$(compose ps -q backend)"
  web_id="$(compose ps -q web)"
  if [[ -n "$backend_id" && -n "$web_id" ]] \
      && [[ "$(docker inspect --format '{{.State.Health.Status}}' "$backend_id" 2>/dev/null)" == "healthy" ]] \
      && [[ "$(docker inspect --format '{{.State.Health.Status}}' "$web_id" 2>/dev/null)" == "healthy" ]]; then
    healthy=1
    break
  fi
  sleep 2
done
(( healthy == 1 )) || die "Previous images did not become healthy; keep the evidence and investigate"

temporary_env="$(mktemp "$DEPLOY_DIR/.env.rollback.XXXXXX")"
trap 'rm -f -- "$temporary_env"' EXIT
awk -v backend="$PREVIOUS_BACKEND_IMAGE" -v web="$PREVIOUS_WEB_IMAGE" '
  BEGIN { backend_written = 0; web_written = 0 }
  /^BACKEND_IMAGE=/ { print "BACKEND_IMAGE=" backend; backend_written = 1; next }
  /^WEB_IMAGE=/ { print "WEB_IMAGE=" web; web_written = 1; next }
  { print }
  END {
    if (!backend_written) print "BACKEND_IMAGE=" backend
    if (!web_written) print "WEB_IMAGE=" web
  }
' "$ENV_FILE" > "$temporary_env"
chmod 600 "$temporary_env"
mv -- "$temporary_env" "$ENV_FILE"
trap - EXIT

printf 'Image rollback completed. Database remained at Flyway version %s.\n' "$current_schema_version"
